### ISSUE TITLE
Win7 SP1 x64, Kodi x86 on VMware 8

### ISSUE THREAD

**Issue by Gelip** [kpl-addons/plugin.video.tvpgo#14]
Win7 64-bit w maszynie wirtualnej VMware 8, Kodi 19.3 x86 bo wersja Kodi x64 nie widzi sieci. Od razu po uruchomieniu wtyczki błąd - Więcej znajdziesz w pliku dziennika zdarzeń a w dzienniku jakiś błąd:
=======================================================
2022-08-27 11:14:49.406 T:2776    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: DLL load failed while importing unicodedata: Parametr jest niepoprawny.
                                                   Traceback (most recent call last):
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\plugin.video.tvpgo\main.py", line 51, in <module>
                                                       from resources.lib.colorpicker import ColorPicker
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\plugin.video.tvpgo\resources\lib\colorpicker.py", line 3, in <module>
                                                       from libka import PathArg
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.libka\lib\libka\__init__.py", line 20, in <module>
                                                       from .addon import Addon, Plugin   # noqa E402
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.libka\lib\libka\addon.py", line 10, in <module>
                                                       from .utils import parse_url
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.libka\lib\libka\utils.py", line 23, in <module>
                                                       from .url import URL, append_url_path
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.libka\lib\libka\url.py", line 34, in <module>
                                                       import yarl
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.libka\lib\libka\..\3rd\yarl\__init__.py", line 1, in <module>
                                                       from ._url import URL, cache_clear, cache_configure, cache_info
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.libka\lib\libka\..\3rd\yarl\_url.py", line 8, in <module>
                                                       import idna
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.idna\lib\idna\__init__.py", line 2, in <module>
                                                       from .core import (
                                                     File "C:\Users\WinXP\AppData\Roaming\Kodi\addons\script.module.idna\lib\idna\core.py", line 3, in <module>
                                                       import unicodedata
                                                   ImportError: DLL load failed while importing unicodedata: Parametr jest niepoprawny.
                                                   -->End of Python script error report<--
                                                   
2022-08-27 11:14:49.420 T:2776     INFO <general>: Python interpreter stopped
2022-08-27 11:14:49.445 T:1504    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.tvpgo/
2022-08-27 11:14:49.525 T:2808    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tvpgo/) failed
=======================================================

Wtyczka działa bez problemu na tej samej wersji Kodi na Android.

**Comment by DenDyGH** [comment]
Sprawdź czy z nową wersją wtyczki jest ten sam problem: https://github.com/kpl-addons/plugin.video.kpl.tvp

**Comment by Gelip** [comment]
To samo na TVP GO i TVP (Libka).

**Comment by heppix** [comment]
Nie wiem czy to ma powiązanie, ale problem przy imporcie jakiejś biblioteki DLL, pochodzi to z tego modułu, który możesz spróbować przeinstalować: https://mirrors.kodi.tv/addons/matrix/script.module.idna/

**Comment by Gelip** [comment]
Zainstalowałem wtyczkę script.module.idna-2.10.0+matrix.1.zip ale nic to nie dało.

**Comment by heppix** [comment]
Ok, w takim razie spróbujemy inaczej. Zainstaluj tę łatkę ze strony MS: https://www.microsoft.com/en-us/download/details.aspx?id=47442

Powinna załatwić sprawę z ładowaniem bibliotek zewnętrznych.

#edit
Łatka o którą chodzi to: KB2533623 aczkolwiek została zastąpiona przez w/w KB3063858

**Comment by Gelip** [comment]
No i działa :-) Po restarcie systemu i odpaleniu Kodi ten pobrał wtyczkę Input Stream Adaptive czy jakoś tak i działa :-)
Dzięki.

**Comment by heppix** [comment]
No i super. Miłego oglądania.
