### ISSUE TITLE
TVPGO not working on osmc/kodi rpi

### ISSUE THREAD

**Issue by krajewmar** [kpl-addons/plugin.video.tvpgo#3]
Plugin is installed, but when I start is I've got an error. In log I see:
Second part - TVP Sport is working well
Could you advice, I'm not programmer :)

`2022-03-26 11:55:31.485 T:778      INFO <general>: initializing python engine.
2022-03-26 11:55:31.952 T:778     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (utils.py, line 253)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvpgo/main.py", line 51, in <module>
                                                       from resources.lib.colorpicker import ColorPicker
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvpgo/resources/lib/colorpicker.py", line 3, in <module>
                                                       from libka import PathArg
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/__init__.py", line 17, in <module>
                                                       from .addon import Addon, Plugin  # noqa E402
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/addon.py", line 10, in <module>
                                                       from .utils import parse_url
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/utils.py", line 253
                                                       if not r or ((port := r['port']) and not port.isdigit()):
                                                                          ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--

2022-03-26 11:55:31.954 T:522      INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-03-26 11:55:31.954 T:522      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "@"
2022-03-26 11:55:31.959 T:522      INFO <general>: CAESinkALSA::Initialize - Opened device "sysdefault"
2022-03-26 11:55:31.960 T:522      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2022-03-26 11:55:31.960 T:522      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2022-03-26 11:55:32.148 T:778      INFO <general>: Python interpreter stopped
2022-03-26 11:55:32.148 T:763     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.tvpgo/
2022-03-26 11:55:36.814 T:779      INFO <general>: initializing python engine.
`

**Comment by rysson** [comment]
@krajewmar, hi, OSMC uses Python 3.7. 
Now our plugins (and libka library) supports Python 3.8+.
We need to think what to do now.

**Comment by krajewmar** [comment]
I 've still got issue. I've updated libka to 0.0.16 trought zip install in Kodi.
2022-03-29 18:42:10.729 T:4281     INFO <general>: initializing python engine.
2022-03-29 18:42:11.248 T:4281    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (utils.py, line 253)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvpgo/main.py", line 51, in <module>
                                                       from resources.lib.colorpicker import ColorPicker
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvpgo/resources/lib/colorpicker.py", line 3, in <module>
                                                       from libka import PathArg
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/__init__.py", line 17, in <module>
                                                       from .addon import Addon, Plugin  # noqa E402
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/addon.py", line 10, in <module>
                                                       from .utils import parse_url
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/utils.py", line 253
                                                       if not r or ((port := r['port']) and not port.isdigit()):
                                                                          ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--

2022-03-29 18:42:11.440 T:4281     INFO <general>: Python interpreter stopped
2022-03-29 18:42:11.453 T:4280    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.tvpgo/
2022-03-29 18:42:11.484 T:488     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tvpgo/) failed

**Comment by rysson** [comment]
@krajewmar it's looks that upgrade fails and you use libka-0.0.15.
Could you put here m5sum of `/home/osmc/.kodi/addons/script.module.libka/lib/libka/utils.py`?

**Comment by krajewmar** [comment]
I foud that addon.xml had 0.0.14 version. I did completly deinstall whole script.module.libka and new install via KPL repository. No should by OK, but still got error.

osmc@osmc:~/.kodi/addons/script.module.libka/lib/libka$ md5sum ./utils.py
8a7526283c474ee7eeb1274fe11ce53c  ./utils.py


2022-03-29 19:10:45.711 T:5759     INFO <general>: initializing python engine.
2022-03-29 19:10:46.434 T:5759    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'get_origin' from 'typing' (/usr/lib/python3.7/typing.py)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvpgo/main.py", line 51, in <module>
                                                       from resources.lib.colorpicker import ColorPicker
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvpgo/resources/lib/colorpicker.py", line 3, in <module>
                                                       from libka import PathArg
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/__init__.py", line 17, in <module>
                                                       from .addon import Addon, Plugin  # noqa E402
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/addon.py", line 10, in <module>
                                                       from .utils import parse_url
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/utils.py", line 23, in <module>
                                                       from .types import KwArgs
                                                     File "/home/osmc/.kodi/addons/script.module.libka/lib/libka/types.py", line 1, in <module>
                                                       from typing import (
                                                   ImportError: cannot import name 'get_origin' from 'typing' (/usr/lib/python3.7/typing.py)
                                                   -->End of Python script error report<--

2022-03-29 19:10:46.635 T:5759     INFO <general>: Python interpreter stopped
2022-03-29 19:10:46.637 T:5758    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.tvpgo/
2022-03-29 19:10:46.667 T:488     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tvpgo/) failed

**Comment by rysson** [comment]
OK, upgrade is OK, now support for 3.7 is not so good. I'll look into.

**Comment by rysson** [comment]
@krajewmar, Try with libka-0.0.17. There ware missing functions in py 3.7 `typing` module.
I don't like supporting old Python, but I understand OSMC upgrades very slow.

**Comment by krajewmar** [comment]
Yes, it's working. Thank you.

**Comment by rysson** [comment]
@krajewmar, you welcome.
Than I close issue for you.
