### ISSUE TITLE
Kanały na żywo nie zawsze się ładują - lista m3u też nie działa.

### ISSUE THREAD

**Issue by zuzia-dev** [kpl-addons/plugin.video.tvpgo#4]
Przy wejściu w kanały na żywo pojawia się błąd. Problem występuje, tyle, że nie za każdym razem. Błąd dotyczy funkcji `get_epgs`

```
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <class 'TypeError'>
  Error Contents: 'NoneType' object is not iterable
  Traceback (most recent call last):
File "/home/zuzia/.kodi/addons/plugin.video.tvpgo/main.py", line 752, in <module>
Main().run()
  File "/home/zuzia/.kodi/addons/script.module.libka/lib/libka/addon.py", line 152, in run
res = self.dispatch(sync=sync)
  File "/home/zuzia/.kodi/addons/script.module.libka/lib/libka/addon.py", line 146, in dispatch
return self.router.sync_dispatch(self.req.url, root=root, missing=missing)
  File "/home/zuzia/.kodi/addons/script.module.libka/lib/libka/routing.py", line 573, in sync_dispatch
return entry.method(*entry.args, **entry.kwargs)
  File "/home/zuzia/.kodi/addons/plugin.video.tvpgo/main.py", line 204, in live
epg_data = {epg.code: epg for epg in self.get_epgs()}
  File "/home/zuzia/.kodi/addons/plugin.video.tvpgo/main.py", line 154, in get_epgs
for e in data['items']:
  TypeError: 'NoneType' object is not iterable
```
Sprawdzałam na PC z Debianem, Kodi 19.4.

**Comment by DenDyGH** [comment]
Trwają prace nad nową wtyczką dla serwisów TVP, ale na pewno się temu przyjrzymy, prawdopodobnie po świętach.

**Comment by Mariusz89B** [comment]
@zuzia-dev Zmien linie 154 w main.py na:
`for e in data.get('items'):`

**Comment by Mariusz89B** [comment]
@zuzia-dev Nalezy zmienic linie 153 na:
```
if tv_code is None or tv_code == data.get('station', {}).get('code'):
                
itemz = data.get('items', None)

if itemz not None:
    for e in itemz:
```

**Comment by zuzia-dev** [comment]
@Mariusz89B jak zwykle nie zawodzisz, dziękuję! Ale zrób, proszę zip dla userów, żeby na święta mieli kanały TVP :)
