### ISSUE TITLE
TVP GO, VOD

### ISSUE THREAD

**Issue by jasiup** [kpl-addons/plugin.video.tvpgo#6]
Przy próbie wgrania czegokolwiek z VOD dostaję (na dwóch urządzeniach Windows 10, Archlinux)
Streamy pozostałe grają OK (Archiwum, Kanały na żywo)

2022-05-06 20:45:06.683 T:11614    INFO <general>: req(GET, 'https://tvpstream.tvp.pl/shared/cdn/tokenizer.php?live=false&time_shift=true&begin=20220430T024000&object_id=51696820&end=20220430T033900', params=None, data=None, json=None, headers={'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.30 Safari/537.36'}, cookies=None)
2022-05-06 20:45:06.840 T:11614   ERROR <general>: EXCEPTION: argument "path" for method "ListItem" must be unicode or str
2022-05-06 20:45:06.844 T:11614   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument "path" for method "ListItem" must be unicode or str
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.tvpgo/main.py", line 755, in <module>
                                                       Main().run()
                                                     File "/var/lib/kodi/.kodi/addons/script.module.libka/lib/libka/addon.py", line 152, in run
                                                       res = self.dispatch(sync=sync)
                                                     File "/var/lib/kodi/.kodi/addons/script.module.libka/lib/libka/addon.py", line 146, in dispatch
                                                       return self.router.sync_dispatch(self.req.url, root=root, missing=missing)
                                                     File "/var/lib/kodi/.kodi/addons/script.module.libka/lib/libka/routing.py", line 573, in sync_dispatch
                                                       return entry.method(*entry.args, **entry.kwargs)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.tvpgo/main.py", line 419, in vod_play
                                                       return self.sort_vod_streams(response)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.tvpgo/main.py", line 426, in sort_vod_streams
                                                       self.play(play_item_url, drm_protocol=protocol)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.tvpgo/main.py", line 433, in play
                                                       play_item = xbmcgui.ListItem(path=url_stream)
                                                   TypeError: argument "path" for method "ListItem" must be unicode or str
                                                   -->End of Python script error report<--

2022-05-06 20:45:07.006 T:11614    INFO <general>: Python interpreter stopped
2022-05-06 20:45:07.033 T:11021   ERROR <general>: Skipped 3 duplicate messages..
2022-05-06 20:45:07.033 T:11021   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tvpgo/vod_play?station_code=INF&record_id=POZ-125106086K]

na Archlinux konfiguracja:

[jasiu@archlinux ~]$ pacman -Q |grep python
dbus-python 1.2.18-3
python 3.10.4-1
python-appdirs 1.4.4-6
python-chardet 4.0.0-5
python-dateutil 2.8.2-4
python-feedparser 6.0.3-1
python-gobject 3.42.1-1
python-idna 3.3-4
python-more-itertools 8.12.0-2
python-ordered-set 4.0.2-6
python-packaging 21.3-1
python-pillow 9.1.0-1
python-pycryptodomex 3.12.0-1
python-pyparsing 3.0.8-1
python-regex 2021.11.10-3
python-requests 2.27.1-1
python-setuptools 1:59.6.0-1
python-sgmllib3k 1.0.0-4
python-simplejson 3.17.6-3
python-six 1.16.0-5
python-urllib3 1.26.9-1
python2 2.7.18-5
python2-gobject 3.36.1-5
[jasiu@archlinux ~]$ pacman -Q |grep kodi
kodi 19.4-4
kodi-addon-inputstream-adaptive-any 19.0.3-1
kodi-addon-vfs-sftp 1.0.0-1
kodi-dev 19.4-4
kodi-platform 20190726.809c5e9-37
kodi-standalone-service 1.135-1

**Comment by DenDyGH** [comment]
Nowa wersja powinna rozwiązać problem, wkrótce pojawi się w repozytorium.
https://github.com/kpl-addons/plugin.video.tvpgo/releases/tag/v1.3.7

**Comment by jasiup** [comment]
> Nowa wersja powinna rozwiązać problem, wkrótce pojawi się w repozytorium. https://github.com/kpl-addons/plugin.video.tvpgo/releases/tag/v1.3.7

Dzięki działa VOD.
Pozdrawiam
