### ISSUE TITLE
Wtyczka nie działa na Linux Xubuntu

### ISSUE THREAD

**Issue by kamillopl** [kpl-addons/plugin.video.tvpgo#7]
Wtyczka nie uruchamia się.

> 2022-06-01 13:51:24.045 T:17718   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'ImportError'>
>                                                    Error Contents: cannot import name '_GenericAlias'
>                                                    Traceback (most recent call last):
>                                                      File "/home/medion/.kodi/addons/plugin.video.tvpgo/main.py", line 51, in <module>
>                                                        from resources.lib.colorpicker import ColorPicker
>                                                      File "/home/medion/.kodi/addons/plugin.video.tvpgo/resources/lib/colorpicker.py", line 3, in <module>
>                                                        from libka import PathArg
>                                                      File "/home/medion/.kodi/addons/script.module.libka/lib/libka/__init__.py", line 17, in <module>
>                                                        from .addon import Addon, Plugin  # noqa E402
>                                                      File "/home/medion/.kodi/addons/script.module.libka/lib/libka/addon.py", line 10, in <module>
>                                                        from .utils import parse_url
>                                                      File "/home/medion/.kodi/addons/script.module.libka/lib/libka/utils.py", line 23, in <module>
>                                                        from .types import KwArgs
>                                                      File "/home/medion/.kodi/addons/script.module.libka/lib/libka/types.py", line 10, in <module>
>                                                        from .py37 import get_origin, get_args
>                                                      File "/home/medion/.kodi/addons/script.module.libka/lib/libka/py37.py", line 5, in <module>
>                                                        from typing import _GenericAlias, Generic
>                                                    ImportError: cannot import name '_GenericAlias'
>                                                    -->End of Python script error report<--

Python w wersji 3.8.13

**Comment by rysson** [comment]
Dzięki, a czy Ci z ręki działa poniższe?
```bash
python3.8 -c 'from typing import _GenericAlias'
```

Czy na pewno Kodi używa Pythona 3.8? Nie tam paru różnych wersji?
Bo to o tyle dziwne, że w Pythononie 3.8.13 w linii 650 jest ta definicja
```python
class _GenericAlias(_Final, _root=True):
```

**Comment by kamillopl** [comment]
Po wykonaniu podanej przez Ciebie komendy konsola niczego nie zwraca.
Przyznam że nie jestem specjalnie obeznany w systemie Linux. Aktualizowałem pythona według poradnika w internecie, no i teraz domyślna wersja to 3.8.13, nie wiem czy to wystarczające.

**Comment by rysson** [comment]
> Po wykonaniu podanej przez Ciebie komendy konsola niczego nie zwraca.
Jak nie ma błędu, to jest ok. Tzn., że wtyczka też powinna pójść. A najwyraźniej nie idzie.
Być może Kodi używa swojego Pythona (co jest dziwne ale nie niemożliwe).

Możesz podać jaka to jest dokładnie platforma? Jaki Linux, jak instalowane Kodi (z paczki, kompilowane ręcznie, a może specjalistyczna dystrybucja)?
